ERROR - 2022-02-13 11:21:16 --> mysqli_sql_exception: Table 'syifa_hidroponik.blogpost' doesn't exist in C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT *\nFROM `...')
#1 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Model.php(213): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\BaseModel.php(583): CodeIgniter\Model->doFindAll(3, 0)
#6 C:\xampp\htdocs\syifa_hidroponik\app\Models\BlogpostModel.php(23): CodeIgniter\BaseModel->findAll(3)
#7 C:\xampp\htdocs\syifa_hidroponik\app\Controllers\Home.php(32): App\Models\BlogpostModel->getBlogpost3()
#8 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(873): App\Controllers\Home->index()
#9 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(408): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(319): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\syifa_hidroponik\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-02-13 11:21:16 --> Table 'syifa_hidroponik.blogpost' doesn't exist
#0 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT *\nFROM `...')
#1 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Model.php(213): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\BaseModel.php(583): CodeIgniter\Model->doFindAll(3, 0)
#6 C:\xampp\htdocs\syifa_hidroponik\app\Models\BlogpostModel.php(23): CodeIgniter\BaseModel->findAll(3)
#7 C:\xampp\htdocs\syifa_hidroponik\app\Controllers\Home.php(32): App\Models\BlogpostModel->getBlogpost3()
#8 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(873): App\Controllers\Home->index()
#9 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(408): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(319): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\syifa_hidroponik\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-02-13 11:38:29 --> mysqli_sql_exception: Duplicate entry 'user1' for key 'PRIMARY' in C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `us...')
#1 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\syifa_hidroponik\app\Controllers\Admin.php(92): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(873): App\Controllers\Admin->createuser()
#9 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(408): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#10 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(319): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\syifa_hidroponik\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-02-13 11:38:29 --> Duplicate entry 'user1' for key 'PRIMARY'
#0 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `us...')
#1 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\syifa_hidroponik\app\Controllers\Admin.php(92): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(873): App\Controllers\Admin->createuser()
#9 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(408): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#10 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(319): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\syifa_hidroponik\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-02-13 12:20:19 --> Too few arguments to function App\Controllers\Admin::cancle(), 0 passed in C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php on line 873 and exactly 1 expected
#0 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(873): App\Controllers\Admin->cancle()
#1 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(408): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#2 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(319): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\syifa_hidroponik\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-02-13 12:40:02 --> Cannot redeclare App\Models\UserModel::cekusername()
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
